# Generated by Django 5.2.4 on 2025-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=10)),
                ('interested', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='farmers',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
