# Generated by Django 5.2.4 on 2025-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
